# Generated by Django 5.0.6 on 2024-06-23 20:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('image_file', models.CharField(default='default.png', max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('instagram_link', models.CharField(max_length=255)),
                ('facebook_link', models.CharField(max_length=255)),
                ('bio', models.TextField(default='', null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
        migrations.CreateModel(
            name='CommsQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'commsquestions',
            },
        ),
        migrations.CreateModel(
            name='ElecsQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'elecsquestions',
            },
        ),
        migrations.CreateModel(
            name='GEASQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'geasquestions',
            },
        ),
        migrations.CreateModel(
            name='MathQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mathquestions',
            },
        ),
        migrations.CreateModel(
            name='CommsOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letter', models.CharField(max_length=1)),
                ('content', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.commsquestions')),
            ],
            options={
                'db_table': 'commsoptions',
            },
        ),
        migrations.CreateModel(
            name='ElecsOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letter', models.CharField(max_length=1)),
                ('content', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.elecsquestions')),
            ],
            options={
                'db_table': 'elecsoptions',
            },
        ),
        migrations.CreateModel(
            name='GEASOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letter', models.CharField(max_length=1)),
                ('content', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.geasquestions')),
            ],
            options={
                'db_table': 'geasoptions',
            },
        ),
        migrations.CreateModel(
            name='MathOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letter', models.CharField(max_length=1)),
                ('content', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.mathquestions')),
            ],
            options={
                'db_table': 'mathoptions',
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=50)),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('difference', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserPost',
            },
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('session_id', models.CharField(max_length=50)),
                ('score_percentage', models.CharField(blank=True, max_length=5, null=True)),
                ('no_correct_answer', models.CharField(blank=True, max_length=5, null=True)),
                ('posted_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('difference', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserResult',
            },
        ),
    ]
